services:
  coinfolio:
    build:
      context: .
      target: base
    command: yarn run dev
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - '4000:4000'
    volumes:
      - ./src:/user/src/app/src
    networks:
      - coinfolio_network
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    networks:
      - coinfolio_network
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  coinfolio_network:
    driver: bridge
