name: Run Pipeline Checks

on: [pull_request]

env:
    IMAGE_TAG: coinfolio-api

jobs:
  pipeline:
    name: linting(prettier & eslint), docker build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Check yarn.lock consistency
        run: git diff --exit-code yarn.lock

      - name: Build the Docker image
        run: docker build -t $IMAGE_TAG --target=create-build .
 
      - name: Run Prettier
        run: docker run $IMAGE_TAG sh -c 'yarn format:verify'
 
      - name: Run ESLint
        run: docker run $IMAGE_TAG sh -c 'yarn lint'
 
      - name: Run tests
        run: docker run $IMAGE_TAG sh -c 'yarn test'
